#!/bin/bash

# Nombre del entorno virtual
VENV_DIR="venv"

# Crear el entorno virtual si no existe
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
    echo "Entorno virtual creado en $VENV_DIR"
fi

# Activar el entorno virtual
# Para bash/zsh:
source "$VENV_DIR/bin/activate"

# Mostrar mensaje de entorno activado
echo "Entorno virtual activado."